#1 Build our production boundle
FROM node:22-alpine as build
WORKDIR /app
COPY package.json ./
RUN npm install
#COPY src src
#COPY public public
COPY . .
CMD [ "npm", "start" ]

# To build the image with voulme mounts for development in CLI

# docker run --rm -d -p 3000:3000 
# -v ./public:/app/public 
# -v ./src:/app/src 
# react-app:dev 

