#1 Build our production boundle
FROM node:22-alpine as build
WORKDIR /app
COPY package.json ./
RUN npm install
#COPY src src
#COPY public public
COPY . .
CMD [ "npm", "start" ]

# To build the image with voulme mounts for development in CLI

# docker run --rm -d -p 3000:3000 
# -v ./public:/app/public 
# -v ./src:/app/src 
# react-app:dev 

# create a volume to persist data
# docker volume create website-data 

# run nginx with volume mount
# docker run  -d -p 3000:80 --name website-main -v website-data:/usr/share/nginx/html nginx:1.27.0 
# docker run  -d -p 3001:80 --name website-readonly1 -v website-data:/usr/share/nginx/html nginx:1.27.0
# docker run  -d -p 3002:80 --name website-readonly2 -v website-data:/usr/share/nginx/html nginx:1.27.0
# docker run  -d -p 3003:80 --name website-readonly3 -v website-data:/usr/share/nginx/html nginx:1.27.0

# docker exec -it website-main sh
# echo "Hello world" > /usr/share/nginx/html/index.html
# cat /usr/share/nginx/html/index.html

# docker exec -it website-readonly1 sh
# cat /usr/share/nginx/html/index.html

